### ISSUE TITLE
GeoPoint queries might be wrong

### ISSUE THREAD

**Issue by Rodiii** [fluttercommunity/firestore_helpers#19]
According to this thread https://stackoverflow.com/questions/46630507/how-to-run-a-geo-nearby-query-with-firestore geohashes must be used in firestore in order to do correct geo-queries.

You're comparing GeoPoints in your queries and not geohashes. So your area filtering is just doing latitude comparisons (according to the stackoverflow thread)

**Comment by escamoteur** [comment]
No that isn't correct it works important that you use Geopoint as datatype.
Have you any other prove besides this post?

**Comment by Rodiii** [comment]
I just verified it for myself by trying an example query. Feel free to check it, too.

Currently, I'm trying to port https://github.com/geofirestore/geofirestore-js to dart in order to get correct geoquery results.

**Comment by escamoteur** [comment]
You used firestore_helpers for this? In our app it works perfectly
Did you create the necessary indexes?

**Comment by Rodiii** [comment]
I used parts of your code to calculate the bounding box. 
In the second screenshot you can see that a document has been included with the longitude 12.x, which should have definitely not in range (you can see the lesser and greaterPoint coordinates in the top left corner). That was proof enough for me that the stackoverflow-thread is still valid, unfortunately.

Of course, I've created indexes before.

<img width="722" alt="image" src="https://user-images.githubusercontent.com/10477273/51078646-07f88880-16b9-11e9-9e42-d54c044c62e0.png">
<img width="954" alt="image" src="https://user-images.githubusercontent.com/10477273/51078637-db447100-16b8-11e9-9a16-2ab0ee9da61c.png">

**Comment by escamoteur** [comment]
Have you tried it without the other constraints? Just the Geopoint? I can only say it works in our Apps

**Comment by IhorKlimov** [comment]
@Rodiii  Firestore doesn't support range filters on multiple fields https://firebase.google.com/docs/firestore/query-data/queries#compound_queries

**Comment by IhorKlimov** [comment]
@escamoteur  I believe @Rodiii is correct, Firestore natively does not support filtering GeoPoints using both *latitude* and *longitude*  fields, as of now https://github.com/firebase/firebase-js-sdk/issues/826

For somebody who's not aware, Firestore currently [doesn't support](https://firebase.google.com/docs/firestore/query-data/queries#compound_queries) range filters on different fields, and abstracting range to GeoPoint type does not fix it, instead, it just uses a *latitude* field of GeoPoint and ignores *longitude*

You can verify that by populating database with random locations around 35.68, 139.76 and running this code

```dart
var docs = await Firestore.instance
    .collection('locations')
    .where("position", isGreaterThanOrEqualTo: GeoPoint(35.68, 139.76))
    .getDocuments();
docs.documents.forEach((d) {
  var g = d.data['position'] as GeoPoint;
  if (g.latitude < 35.68 || g.longitude < 139.76) {
    print('${g.latitude} ${g.longitude}');
  }
});
```
And print statements will be called because of longitudes

So as I understand, firestore_helpers isn't a very optimized solution for this problem, where you fetch __a lot__ more than you need, as it does client-side filtering for longitudes. Thus, you can expect a very poor performance for your geo-search. Whereas the real solution for this problem would be __geohashes__, which would be a server-side filtering for both latitudes and longitudes

**Comment by escamoteur** [comment]
@IhorKlimov Thanks for the reference to the discussion on the firebase repo. If that is the case then we just did not find this because of our limited datas et or because we always also use a client site filter. I will add a warning to the README. I think for a lot of simple applications its still useful.

**Comment by chinu999** [comment]
hi can anyone tell me how can i retrieve geopoint from firebase.
i am getting an error "type Geopoint is not a subtype of type String".In phone

code to add:
IconButton(
            icon: Icon(Icons.search, color: Colors.black), onPressed: (){
            Firestore.instance.collection('Location').add({
              'location':
              new GeoPoint(position.latitude,position.longitude),
            });

          },),

code to retrieve:
class _PageeetState extends State<Pageee> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: StreamBuilder(
        stream: Firestore.instance.collection('Location'.toString()).snapshots(),
        builder: (BuildContext context, AsyncSnapshot<QuerySnapshot> snapshot) {
          if (!snapshot.hasData) return Text("There is no expense");
          return ListView(children: getExpenseItems(snapshot));
        },
      ),
    );
  }

  getExpenseItems(AsyncSnapshot<QuerySnapshot> snapshot) {
    return snapshot.data.documents
        .map(
          (doc) => Card(

        shape: RoundedRectangleBorder(
          borderRadius: BorderRadius.circular(20.0),),
        child: Padding(
          padding: const EdgeInsets.all(8.0),
          child: ListTile(
            title: Text.rich(
              TextSpan(
                text: 'location: ', // default text style
                children: <TextSpan>[
                  TextSpan(text: doc['location'],),
                ],
              ),
            ),
          ),
        ),
      ),
    )
        .toList();
  }
}
