### ISSUE TITLE
error showing in after addin in depandacy

### ISSUE THREAD

**Issue by hitanshu1** [fluttercommunity/firestore_helpers#21]
error showing when i add following dependencies 

 cupertino_icons: ^0.1.2
  cloud_firestore: ^0.9.0
  firebase_auth: ^0.8.0+1
  flutter_swiper:
  intl:
  firebase_database:
  datetime_picker_formfield:
  paytm:
  http:
  flutter_staggered_grid_view:
  firestore_helpers: ^3.0.0

**Comment by netwiser** [comment]
It is because the breaking change introduced by cloud_firestore 0.9.0 and firebase_auth 0.8.0, I tried to upgrade the same however clourstore_helper depends on cloud_firestore 0.6.6 only.

@author, please bump up the version. Thanks

**Comment by escamoteur** [comment]
fixed with 3.1.0 thanks to the PR by @netwiser

**Comment by bderbidge** [comment]
Needs to be updated again because I got this error when trying to add to project.

Because firestore_helpers >=3.1.0 depends on cloud_firestore ^0.9.0 and project depends on cloud_firestore ^0.11.0+2, firestore_helpers >=3.1.0 is forbidden.

So, because project depends on firestore_helpers ^3.1.0, version solving failed.
pub get failed (1)
exit code 1
